### ISSUE TITLE
Question about WaveGlow

### ISSUE THREAD

**Issue by leijue222** [begeekmyfriend/tacotron2#35]
I have trained WaveRNN and got good results. Since WaveGlow's inference speed on GPU is faster than WaveRNN, so I want to train a WaveGlow vocoder.

For your WaveGlow repository, I made the following modifications to make training possible:
1. Move the `quant` and `mel` data to it; (Data used to train WaveRNN)
2. Change config.json `mel_pad_val: -5.0`; (I set `voc_pad_val=-5.0` when training WaveRNN)
3. Add `z = z.type(torch.cuda.HalfTensor)` before [glow.py-L116](https://github.com/begeekmyfriend/waveglow/blob/315c56ac65c1e36bbd985be777295fe01ecef228/glow.py#L116) to solve the training error of `input type (torch.cuda.ShortTensor) and weight type (torch.cuda.HalfTensor) should be the same`.

After 13 hours of training, 21 epochs, logs is:
![屏幕截图 2021-01-13 11:04:40](https://user-images.githubusercontent.com/30276789/104401475-3d2d5f00-558f-11eb-9f49-e52628079278.png)

When using `--is_fp16 ` to inference, the wav result is all silent.
If not using `--is_fp16 ` to inference, the wav result is all noise.

Did I do something wrong? Could you give me some suggestions?

----

Maybe the training is not enough. Now 24 hours, 24K steps, 40 epochs.
Sometimes still will have warning of `Gradient overflow.  Skipping step, loss scaler 0 reducing loss scale to 1024.0`

**Comment by begeekmyfriend** [comment]
The warning is just about gradient overflow and the program would clip the gradient under 1.0 threshold. Do not care about it since it only occurs at the beginning of the training.
Since I am not engage in TTS now I am not familiar with this project. I think you'd better remove `z = z.type(torch.cuda.HalfTensor)` for comparison to train out a baseline result first. Good luck.
